module.exports = [
    {
        "city": "Delhi", 
        "lat": "28.6600", 
        "lng": "77.2300", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Delhi", 
        "capital": "admin", 
        "population": "29617000", 
        "population_proper": "16753235"
      }, 
      {
        "city": "Mumbai", 
        "lat": "18.9667", 
        "lng": "72.8333", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Mahārāshtra", 
        "capital": "admin", 
        "population": "23355000", 
        "population_proper": "12478447"
      }, 
      {
        "city": "Kolkāta", 
        "lat": "22.5411", 
        "lng": "88.3378", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "West Bengal", 
        "capital": "admin", 
        "population": "17560000", 
        "population_proper": "4496694"
      }, 
      {
        "city": "Bangalore", 
        "lat": "12.9699", 
        "lng": "77.5980", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Karnātaka", 
        "capital": "admin", 
        "population": "13707000", 
        "population_proper": "8443675"
      }, 
      {
        "city": "Chennai", 
        "lat": "13.0825", 
        "lng": "80.2750", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Tamil Nādu", 
        "capital": "admin", 
        "population": "11324000", 
        "population_proper": "6727000"
      }, 
      {
        "city": "Hyderābād", 
        "lat": "17.3667", 
        "lng": "78.4667", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Telangana", 
        "capital": "admin", 
        "population": "9746000", 
        "population_proper": "6993262"
      }, 
      {
        "city": "Pune", 
        "lat": "18.5196", 
        "lng": "73.8553", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Mahārāshtra", 
        "capital": "", 
        "population": "7764000", 
        "population_proper": "3124458"
      }, 
      {
        "city": "Ahmedabad", 
        "lat": "23.0300", 
        "lng": "72.5800", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Gujarāt", 
        "capital": "minor", 
        "population": "7410000", 
        "population_proper": "5570585"
      }, 
      {
        "city": "Sūrat", 
        "lat": "21.1700", 
        "lng": "72.8300", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Gujarāt", 
        "capital": "", 
        "population": "5807000", 
        "population_proper": "4466826"
      }, 
      {
        "city": "Lucknow", 
        "lat": "26.8470", 
        "lng": "80.9470", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Uttar Pradesh", 
        "capital": "admin", 
        "population": "3382000", 
        "population_proper": "3382000"
      }, 
      {
        "city": "Jaipur", 
        "lat": "26.9167", 
        "lng": "75.8667", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Rājasthān", 
        "capital": "admin", 
        "population": "3073350", 
        "population_proper": "3073350"
      }, 
      {
        "city": "Cawnpore", 
        "lat": "26.4725", 
        "lng": "80.3311", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Uttar Pradesh", 
        "capital": "", 
        "population": "2701324", 
        "population_proper": "2701324"
      }, 
      {
        "city": "Mirzāpur", 
        "lat": "25.1500", 
        "lng": "82.5800", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Uttar Pradesh", 
        "capital": "", 
        "population": "2496970", 
        "population_proper": "2496970"
      }, 
      {
        "city": "Nāgpur", 
        "lat": "21.1539", 
        "lng": "79.0831", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Mahārāshtra", 
        "capital": "", 
        "population": "2405665", 
        "population_proper": "2405665"
      }, 
      {
        "city": "Ghāziābād", 
        "lat": "28.6667", 
        "lng": "77.4167", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Uttar Pradesh", 
        "capital": "", 
        "population": "2381452", 
        "population_proper": "2381452"
      }, 
      {
        "city": "Indore", 
        "lat": "22.7206", 
        "lng": "75.8472", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Madhya Pradesh", 
        "capital": "", 
        "population": "2201927", 
        "population_proper": "2201927"
      }, 
      {
        "city": "Vadodara", 
        "lat": "22.3000", 
        "lng": "73.2000", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Gujarāt", 
        "capital": "", 
        "population": "2065771", 
        "population_proper": "2065771"
      }, 
      {
        "city": "Vishākhapatnam", 
        "lat": "17.7333", 
        "lng": "83.3167", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Andhra Pradesh", 
        "capital": "", 
        "population": "2035922", 
        "population_proper": "2035922"
      }, 
      {
        "city": "Bhopāl", 
        "lat": "23.2500", 
        "lng": "77.4167", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Madhya Pradesh", 
        "capital": "admin", 
        "population": "1883381", 
        "population_proper": "1883381"
      }, 
      {
        "city": "Chinchvad", 
        "lat": "18.6278", 
        "lng": "73.8131", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Mahārāshtra", 
        "capital": "", 
        "population": "1729320", 
        "population_proper": "1729320"
      }, 
      {
        "city": "Patna", 
        "lat": "25.6100", 
        "lng": "85.1414", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Bihār", 
        "capital": "admin", 
        "population": "1684222", 
        "population_proper": "1684222"
      }, 
      {
        "city": "Ludhiāna", 
        "lat": "30.9083", 
        "lng": "75.8486", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Punjab", 
        "capital": "", 
        "population": "1649000", 
        "population_proper": "1545368"
      }, 
      {
        "city": "Āgra", 
        "lat": "27.1800", 
        "lng": "78.0200", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Uttar Pradesh", 
        "capital": "", 
        "population": "1585705", 
        "population_proper": "1585705"
      }, 
      {
        "city": "Kalyān", 
        "lat": "19.2502", 
        "lng": "73.1602", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Mahārāshtra", 
        "capital": "", 
        "population": "1576614", 
        "population_proper": "1576614"
      }, 
      {
        "city": "Madurai", 
        "lat": "9.9197", 
        "lng": "78.1194", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Tamil Nādu", 
        "capital": "minor", 
        "population": "1561129", 
        "population_proper": "1561129"
      }, 
      {
        "city": "Jamshedpur", 
        "lat": "22.8000", 
        "lng": "86.1833", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Jharkhand", 
        "capital": "", 
        "population": "1558000", 
        "population_proper": "1558000"
      }, 
      {
        "city": "Nāsik", 
        "lat": "20.0000", 
        "lng": "73.7833", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Mahārāshtra", 
        "capital": "", 
        "population": "1486053", 
        "population_proper": "1486053"
      }, 
      {
        "city": "Farīdābād", 
        "lat": "28.4333", 
        "lng": "77.3167", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Haryāna", 
        "capital": "", 
        "population": "1394000", 
        "population_proper": "1394000"
      }, 
      {
        "city": "Aurangābād", 
        "lat": "19.8800", 
        "lng": "75.3200", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Mahārāshtra", 
        "capital": "", 
        "population": "1371330", 
        "population_proper": "1371330"
      }, 
      {
        "city": "Rājkot", 
        "lat": "22.2969", 
        "lng": "70.7984", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Gujarāt", 
        "capital": "", 
        "population": "1335397", 
        "population_proper": "1335397"
      }, 
      {
        "city": "Meerut", 
        "lat": "28.9900", 
        "lng": "77.7000", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Uttar Pradesh", 
        "capital": "", 
        "population": "1305429", 
        "population_proper": "1305429"
      }, 
      {
        "city": "Jabalpur", 
        "lat": "23.1667", 
        "lng": "79.9333", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Madhya Pradesh", 
        "capital": "", 
        "population": "1267564", 
        "population_proper": "1267564"
      }, 
      {
        "city": "Thāne", 
        "lat": "19.1800", 
        "lng": "72.9633", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Mahārāshtra", 
        "capital": "", 
        "population": "1261517", 
        "population_proper": "1261517"
      }, 
      {
        "city": "Dhanbād", 
        "lat": "23.7928", 
        "lng": "86.4350", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Jharkhand", 
        "capital": "", 
        "population": "1246000", 
        "population_proper": "219636"
      }, 
      {
        "city": "Allahābād", 
        "lat": "25.4550", 
        "lng": "81.8400", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Uttar Pradesh", 
        "capital": "", 
        "population": "1201000", 
        "population_proper": "1073438"
      }, 
      {
        "city": "Vārānasi", 
        "lat": "25.3189", 
        "lng": "83.0128", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Uttar Pradesh", 
        "capital": "", 
        "population": "1198491", 
        "population_proper": "1198491"
      }, 
      {
        "city": "Srīnagar", 
        "lat": "34.0911", 
        "lng": "74.8061", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Jammu and Kashmīr", 
        "capital": "admin", 
        "population": "1180570", 
        "population_proper": "1180570"
      }, 
      {
        "city": "Amritsar", 
        "lat": "31.6167", 
        "lng": "74.8500", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Punjab", 
        "capital": "", 
        "population": "1132383", 
        "population_proper": "1132383"
      }, 
      {
        "city": "Alīgarh", 
        "lat": "27.8800", 
        "lng": "78.0800", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Uttar Pradesh", 
        "capital": "", 
        "population": "1131160", 
        "population_proper": "1131160"
      }, 
      {
        "city": "Bhiwandi", 
        "lat": "19.3000", 
        "lng": "73.0667", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Mahārāshtra", 
        "capital": "", 
        "population": "1125898", 
        "population_proper": "1125898"
      }, 
      {
        "city": "Gwalior", 
        "lat": "26.2150", 
        "lng": "78.1931", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Madhya Pradesh", 
        "capital": "", 
        "population": "1101981", 
        "population_proper": "1101981"
      }, 
      {
        "city": "Bhilai", 
        "lat": "21.2167", 
        "lng": "81.4333", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Chhattīsgarh", 
        "capital": "", 
        "population": "1097000", 
        "population_proper": "1097000"
      }, 
      {
        "city": "Hāora", 
        "lat": "22.5900", 
        "lng": "88.3100", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "West Bengal", 
        "capital": "", 
        "population": "1077075", 
        "population_proper": "1077075"
      }, 
      {
        "city": "Rānchi", 
        "lat": "23.3556", 
        "lng": "85.3347", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Jharkhand", 
        "capital": "admin", 
        "population": "1073440", 
        "population_proper": "1073440"
      }, 
      {
        "city": "Bezwāda", 
        "lat": "16.5167", 
        "lng": "80.6167", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Andhra Pradesh", 
        "capital": "", 
        "population": "1048240", 
        "population_proper": "1048240"
      }, 
      {
        "city": "Chandīgarh", 
        "lat": "30.7353", 
        "lng": "76.7911", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Chandīgarh", 
        "capital": "admin", 
        "population": "1026459", 
        "population_proper": "1026459"
      }, 
      {
        "city": "Mysore", 
        "lat": "12.3086", 
        "lng": "76.6531", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Karnātaka", 
        "capital": "", 
        "population": "1014227", 
        "population_proper": "1014227"
      }, 
      {
        "city": "Raipur", 
        "lat": "21.2379", 
        "lng": "81.6337", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Chhattīsgarh", 
        "capital": "admin", 
        "population": "1010087", 
        "population_proper": "1010087"
      }, 
      {
        "city": "Kota", 
        "lat": "25.1800", 
        "lng": "75.8300", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Rājasthān", 
        "capital": "", 
        "population": "1001694", 
        "population_proper": "1001694"
      }, 
      {
        "city": "Bareilly", 
        "lat": "28.3640", 
        "lng": "79.4150", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Uttar Pradesh", 
        "capital": "", 
        "population": "1000000", 
        "population_proper": "1000000"
      }, 
      {
        "city": "Jodhpur", 
        "lat": "26.2918", 
        "lng": "73.0168", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Rājasthān", 
        "capital": "", 
        "population": "995000", 
        "population_proper": "921476"
      }, 
      {
        "city": "Coimbatore", 
        "lat": "11.0000", 
        "lng": "76.9667", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Tamil Nādu", 
        "capital": "", 
        "population": "959823", 
        "population_proper": "959823"
      }, 
      {
        "city": "Dispur", 
        "lat": "26.1500", 
        "lng": "91.7700", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Assam", 
        "capital": "admin", 
        "population": "957352", 
        "population_proper": "957352"
      }, 
      {
        "city": "Guwāhāti", 
        "lat": "26.1667", 
        "lng": "91.7667", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Assam", 
        "capital": "", 
        "population": "957352", 
        "population_proper": "957352"
      }, 
      {
        "city": "Solāpur", 
        "lat": "17.6833", 
        "lng": "75.9167", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Mahārāshtra", 
        "capital": "", 
        "population": "951558", 
        "population_proper": "951558"
      }, 
      {
        "city": "Trichinopoly", 
        "lat": "10.8269", 
        "lng": "78.6928", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Tamil Nādu", 
        "capital": "", 
        "population": "916857", 
        "population_proper": "916857"
      }, 
      {
        "city": "Hubli", 
        "lat": "15.3600", 
        "lng": "75.1250", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Karnātaka", 
        "capital": "", 
        "population": "890000", 
        "population_proper": "792804"
      }, 
      {
        "city": "Jalandhar", 
        "lat": "31.3256", 
        "lng": "75.5792", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Punjab", 
        "capital": "", 
        "population": "873725", 
        "population_proper": "873725"
      }, 
      {
        "city": "Bhubaneshwar", 
        "lat": "20.2644", 
        "lng": "85.8281", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Odisha", 
        "capital": "admin", 
        "population": "837737", 
        "population_proper": "837737"
      }, 
      {
        "city": "Bhayandar", 
        "lat": "19.3000", 
        "lng": "72.8500", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Mahārāshtra", 
        "capital": "", 
        "population": "814655", 
        "population_proper": "814655"
      }, 
      {
        "city": "Morādābād", 
        "lat": "28.8418", 
        "lng": "78.7568", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Uttar Pradesh", 
        "capital": "", 
        "population": "787000", 
        "population_proper": "721139"
      }, 
      {
        "city": "Kolhāpur", 
        "lat": "16.7000", 
        "lng": "74.2333", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Mahārāshtra", 
        "capital": "", 
        "population": "750000", 
        "population_proper": "561841"
      }, 
      {
        "city": "Thiruvananthapuram", 
        "lat": "8.5000", 
        "lng": "76.8997", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Kerala", 
        "capital": "admin", 
        "population": "743691", 
        "population_proper": "743691"
      }, 
      {
        "city": "Sahāranpur", 
        "lat": "29.9640", 
        "lng": "77.5460", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Uttar Pradesh", 
        "capital": "", 
        "population": "705478", 
        "population_proper": "705478"
      }, 
      {
        "city": "Warangal", 
        "lat": "17.9756", 
        "lng": "79.6011", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Telangana", 
        "capital": "", 
        "population": "704570", 
        "population_proper": "704570"
      }, 
      {
        "city": "Salem", 
        "lat": "11.6500", 
        "lng": "78.1667", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Tamil Nādu", 
        "capital": "", 
        "population": "693236", 
        "population_proper": "693236"
      }, 
      {
        "city": "Mālegaon", 
        "lat": "20.5500", 
        "lng": "74.5500", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Mahārāshtra", 
        "capital": "", 
        "population": "690844", 
        "population_proper": "435362"
      }, 
      {
        "city": "Kochi", 
        "lat": "9.9667", 
        "lng": "76.2833", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Kerala", 
        "capital": "", 
        "population": "677381", 
        "population_proper": "677381"
      }, 
      {
        "city": "Gorakhpur", 
        "lat": "26.7611", 
        "lng": "83.3667", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Uttar Pradesh", 
        "capital": "", 
        "population": "673446", 
        "population_proper": "673446"
      }, 
      {
        "city": "Shimoga", 
        "lat": "13.9304", 
        "lng": "75.5600", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Karnātaka", 
        "capital": "", 
        "population": "654055", 
        "population_proper": "319550"
      }, 
      {
        "city": "Tiruppūr", 
        "lat": "11.1075", 
        "lng": "77.3398", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Tamil Nādu", 
        "capital": "", 
        "population": "650000", 
        "population_proper": "444543"
      }, 
      {
        "city": "Guntūr", 
        "lat": "16.3000", 
        "lng": "80.4500", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Andhra Pradesh", 
        "capital": "", 
        "population": "647508", 
        "population_proper": "647508"
      }, 
      {
        "city": "Raurkela", 
        "lat": "22.2492", 
        "lng": "84.8828", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Odisha", 
        "capital": "", 
        "population": "625831", 
        "population_proper": "483629"
      }, 
      {
        "city": "Mangalore", 
        "lat": "12.8703", 
        "lng": "74.8806", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Karnātaka", 
        "capital": "", 
        "population": "623841", 
        "population_proper": "623841"
      }, 
      {
        "city": "Nānded", 
        "lat": "19.1500", 
        "lng": "77.3333", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Mahārāshtra", 
        "capital": "", 
        "population": "623708", 
        "population_proper": "550564"
      }, 
      {
        "city": "Cuttack", 
        "lat": "20.4500", 
        "lng": "85.8667", 
        "country": "India", 
        "iso2": "IN", 
        "admin_name": "Odisha", 
        "capital": "", 
        "population": "606007", 
        "population_proper": "606007"
      }, 
    
]

